# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'Greet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ClaySDK', '~> 1.10'

  # Pods for Greet

end
